apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nonodede-gitops
  description: This is GitOps manifest for nonodede   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: nonodede
    backstage.io/kubernetes-id: nonodede 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: katka-rhtap/nonodede-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nonodede
