apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nonodede
  janus-idp.io/tekton: nonodede
  backstage.io/kubernetes-id: nonodede
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nonodede
resources:
- deployment.yaml
- route.yaml
- service.yaml
